Bulk mempool txs
mempool/electrs pull request #18
Opened 2023-07-22 05:34 UTC by mononaut

Synchronizing the mempool one-by-one with individual `/tx/:txid` requests is extremely slow when the mempool is large.

This PR adds a (very naïve) bulk `/mempool/txs` endpoint which returns the entire mempool in a single query.

Ideally this would be a paginated endpoint with more manageable response sizes, but the single bulk endpoint does seem to work for now.

This is used in [a draft PR in the mempool backend](https://github.com/mempool/mempool/pull/4025) to massively reduce startup time.

2023-07-22 06:20 UTC, junderw approved these changes
This change looks solid.

The only thing I might worry about is external abuse. When the mempool is large, if someone hammers this endpoint we might have problems.

Other than that, the change is valid, and no nits about the Rust.

2023-07-22 06:23 UTC, mononaut commented
Good point, we probably don't want to expose this externally at all

2023-07-22 07:14 UTC, junderw commented
I had a similar dillema on the #17 PR, Allowing anyone in the public to know the exact version of our running instance is not very secure, so:

1. It only available via a feature flag.
2. It uses an `internal` path to start off with so we can use nginx to reject anything beyond /internal/*

Perhaps we should adopt a similar approach here. The front end should not access it, and normal people who install electrs shouldn't have an endpoint doxxing their versions and allowing DoS etc.

2023-07-22 07:15 UTC, junderw commented
The `version-api` feature name could be `internal-apis` but I wasn't thinking about multiple features.

2023-07-23 03:38 UTC, wiz commented
Yeah we will have to restrict this in the nginx configuration to trusted things only

2023-07-23 04:01 UTC, wiz requested changes
Tested NACK @ 5c1dd14620dc117d5c9b2ea836ce81e8948f599e

The API worked well after a few unsuccessful tries, but the first few requests to the new `/api/mempool/txs` endpoint returned an empty `[]` with the following error printed - if the mempool is not yet available it should probably return HTTP 503 instead of an HTTP 200 with empty response. Also noteworth was the request to return the full mempool caused electrs to hang for about 20 seconds, which I suppose is fine if we lock it down to localhost and only request it when the mempool backend starts.
```
WARN - failed to get 284824 transactions: getrawtransaction RPC error: {"code":-5,"message":"No such mempool or blockchain transaction. Use gettransaction for wallet transactions."}
```

2023-07-23 06:20 UTC, mononaut commented
> `WARN - failed to get 284824 transactions: getrawtransaction RPC error: {"code":-5,"message":"No such mempool or blockchain transaction. Use gettransaction for wallet transactions."}`

I think this error is unrelated.

Returning an empty array when the mempool hasn't finished loading isn't ideal, but I'm not sure what the best approach would be to detect that situation and return a 503 instead.

2023-07-23 06:22 UTC, mononaut commented
I've just push a change which switches the full mempool endpoint to /mempool/txs/all, and adds a new paginated endpoint at /mempool/txs/(:txid).

This returns batches of 10k mempool transactions, starting after the provided txid (if any), which lets a client iterate over the full mempool in efficient batched queries.

To support this, the PR swaps the mempool `txstore` HashMap for a BTreeMap which maintains a stable ordering of elements.

2023-07-23 07:27 UTC, mononaut commented
rebased

2023-07-23 09:15 UTC, junderw commented on src/new_index/mempool.rs
> +        }
```suggestion
        self.txstore.range((start_bound, Unbounded))
            .take(n)
            .for_each(|(_, value)| {
                page.push(value.clone());
            });
```

2023-07-23 09:19 UTC, junderw commented
BTreeMap shouldn't cause any issues with existing code, but I'm not too sure about mempool "ordering" by txid...

New transactions can easily slide into the area of the 10k you just got.

2023-07-23 09:20 UTC, junderw commented
(If we want to go down the ordering route... we should probably sort by ascending `firstSeen`... though I'm not sure how that'll work...)

2023-07-23 09:28 UTC, mononaut commented
As long the BTreeMap doesn't break other parts of the codebase or reduce performance too much, I think it's acceptable to miss newer transactions.

This is only intended for an initial sync, so it just needs to keep the order of existing transactions stable enough to get the majority of the mempool without wasting requests, and any new arrivals can be picked up individually on the next update.

2023-07-23 09:28 UTC, softsimon commented
> New transactions can easily slide into the area of the 10k you just got.

I think that doesn't matter. The point is to get the bulk 90%? of the mempool "instantly" and then continue on from there as we usually do with fetching individually what's missing.

2023-07-23 09:31 UTC, junderw commented
Ok. Well, it's going to be internal anyways.

Also, some fmt fixes are needed `cargo fmt` please.

2023-07-24 05:53 UTC, wiz approved these changes
Tested ACK @ e86f618319b8b56eaef32f8979b8e781953d1df6

```
INFO - handle GET /mempool/txids
INFO - handle GET /mempool/txids
INFO - handle GET /mempool/txs
INFO - handle GET /mempool/txs
INFO - handle GET /mempool/txs/c8c19c8674d5738c9f9a1258f3e0aa82de78b808a15685173b40463fe8053c0a
INFO - handle GET /mempool/txs/762c3477531a3280b9f7280c019fd339149c8c93c1c8fac3c78fb1ea98bc3c0a
INFO - handle GET /mempool/txs/8cc6e2539f3195d1cf75172b5cee89d6776c416d78ea91de65ec8e4a6c866c14
INFO - handle GET /mempool/txs/3711cecc061e73e577d821e8fbfac5fdcb56e5e7e0a512316cbb3f2707656c14
INFO - handle GET /mempool/txs/f991d9afefe5b74f394a88da21b802eab36ff270bd74b8bcf7563ac0b1545a1e
INFO - handle GET /mempool/txs/2f0f9f5443507ee521a41389926d6109fa6fd16713aa185dc16a7a0532765b1e
INFO - handle GET /mempool/txs/ddfedfe011d3b998d3f72eacaad2a16711be6fed823bdbcc876bbda7c9941528
INFO - handle GET /mempool/txs/e4861351c2ed250f853759c8219c3757695fccec464bac7bdba0f1d10dc71528
INFO - handle GET /mempool/txs/1c59082db684c4ccec8232ac99eda080483a06c6b390f98ebd0928dd30f38d31
INFO - handle GET /mempool/txs/1c59082db684c4ccec8232ac99eda080483a06c6b390f98ebd0928dd30f38d31
INFO - handle GET /mempool/txs/973fe0bb7e25a2199e5dfe907c17079d3a430ca268f0580a7111bc3cd028223b
INFO - handle GET /mempool/txs/973fe0bb7e25a2199e5dfe907c17079d3a430ca268f0580a7111bc3cd028223b
INFO - handle GET /mempool/txs/88c950e037b373d1281f51054a10465506b9a7c21b8c8a7d2688753b72a6b844
INFO - handle GET /mempool/txs/88c950e037b373d1281f51054a10465506b9a7c21b8c8a7d2688753b72a6b844
INFO - handle GET /mempool/txs/8e499d23715280bdd7e1f50cd4079df604c1e381a5326461056d4352eaf0594e
INFO - handle GET /mempool/txs/8e499d23715280bdd7e1f50cd4079df604c1e381a5326461056d4352eaf0594e
INFO - handle GET /mempool/txs/1b174243e5568772add0294db461e8677f69f8ddf5d16cf5a1abc2562f56f657
INFO - handle GET /mempool/txs/1b174243e5568772add0294db461e8677f69f8ddf5d16cf5a1abc2562f56f657
INFO - handle GET /mempool/txs/a343a6a0495dcf7d32e0359a25503c3a9ee6082a9894c587807863a2a284b161
INFO - handle GET /mempool/txs/a343a6a0495dcf7d32e0359a25503c3a9ee6082a9894c587807863a2a284b161
INFO - handle GET /mempool/txs/49a70f876cc5059b1722cc4b9b7b790a6186a6e7828c4d470ffa64b50e75836b
INFO - handle GET /mempool/txs/952b3e49e4fa3df878a0a114cf64e5a220e29a73e7446661ae793994ebbe836b
INFO - handle GET /mempool/txs/3f45b788eba80d345cf35ebd45d07fe7cf4949578f713d0872365b1f62093c75
INFO - handle GET /mempool/txs/34fb520670972e3528962d39484b663aaffbe6ddb449eeeec3fffe7bf0ef3b75
INFO - handle GET /mempool/txs/efdbf42ad329e473e7c30246664fa516fe9748735704f44d131c00f6f0e2027f
INFO - handle GET /mempool/txs/bf5f15b0b6d280fb5b4deacbcc16846f9f093706e5e79b67d6060bc7f690037f
INFO - handle GET /mempool/txs/447b8633e135747f2d0cce4233244494c8e8fb53fbc8d6d954ff8cb9f749d888
INFO - handle GET /mempool/txs/1f9d51fbf95542c377a86ab889ccd897f33aeed56772915e84e2de798886d888
INFO - handle GET /mempool/txs/7b8d7303056e711ce360ed66372612d3e4a8ce81c5ec848c7d400b992245af92
INFO - handle GET /mempool/txs/3280e23ea488e5e033e6a715cba07d0cc9481976f5fb35051ae51ec2050faf92
INFO - handle GET /mempool/txs/49e277d2644a8c7e40db519cae1fd02e72bb730b9947b0e54a6cccd19a399a9c
INFO - handle GET /mempool/txs/d634ec2c7da22077ebda3205b962897018df1896d68daf35b606e8b66cd49a9c
INFO - handle GET /mempool/txs/824b4c88d2c8f71ed87aecfd0afdd650cce8d54a761fed3fc7e694002543b5a6
INFO - handle GET /mempool/txs/824b4c88d2c8f71ed87aecfd0afdd650cce8d54a761fed3fc7e694002543b5a6
INFO - handle GET /mempool/txs/3ec13a7ddb6d4e1e56fcd5822395f8205db73adb95d86108f28dc4aab229bab0
INFO - handle GET /mempool/txs/3ec13a7ddb6d4e1e56fcd5822395f8205db73adb95d86108f28dc4aab229bab0
INFO - handle GET /mempool/txs/35d67145ca7c0ff76da7973fdbf1b533d5298842a49a5d3e1790910b6ad2d2ba
INFO - handle GET /mempool/txs/f051ea7510d95566d80c376e078ba9fdb5b102441c0666b65d97b9dd373fd2ba
INFO - handle GET /mempool/txs/a94148c773fae5ddc488e4d834afbac5f200e3bcd3c614b2316d36b533a9c3c4
INFO - handle GET /mempool/txs/3c6fd7700faab1176b3efcb39b7cf22bbe9ab09d1a4e5f7a72f8aa61d365c2c4
INFO - handle GET /mempool/txs/083c1eef135e172563f67c556b6193393ed9d32e27a533cafa6f7bd08e1383ce
INFO - handle GET /mempool/txs/81f4e8b36d8bf4225f33ee1c2f0d9245f97b7ae3cda0cee561d17fd76e6681ce
INFO - handle GET /mempool/txs/f7f75d59ed91c2206b6a8cbd973b8fe86af96491482dc129c9f54c2db4d908d8
INFO - handle GET /mempool/txs/a9a0af3b713309e510315941856572c2ef8ec5e6a574453b071f3350b05d08d8
INFO - handle GET /mempool/txs/5f30db2434583311e77efaa683935d81c43d02884819323f8d4d29a5a221fae0
INFO - handle GET /mempool/txs/a9d6b9d1e68af3022d848f32780fbd8f13a00edf62029f33679ebff8b635f9e0
INFO - handle GET /mempool/txs/a341c3549962391a4595e6d424d3724c27752a262b8600b424d34bca1709a9e9
INFO - handle GET /mempool/txs/f717cc17cf33367b20344f507ff36973e2fc3e7b37d41b4bee4b851324a3a6e9
INFO - handle GET /mempool/txs/557d3db88adc6b1600c9477f39ee6de1a7e0208f8008d1aaba2d07eb4b0971f2
INFO - handle GET /mempool/txs/5f8e7b4d98d6313fa1660775fb938746ad73332752a95ec02ba467c1c1b26ef2
INFO - handle GET /mempool/txs/d1f12503762db6f761b7f98ba6430121a687e83b5440ec044d6efa8d3cd825fb
INFO - handle GET /mempool/txs/3a3fa45329b58ea51637a1b42f449369b0d18d29742d605a8d2c769720aa27fb
INFO - handle GET /mempool/txs/00d25c65b1a5badbf74abb66323504337b4ccc67a7ac729eb8a1cd8791e4ffff
INFO - handle GET /mempool/txs/00d25c65b1a5badbf74abb66323504337b4ccc67a7ac729eb8a1cd8791e4ffff
INFO - handle GET /mempool/txids
```

```
Jul 24 05:49:43 [48328] DEBUG: Updating mempool...
Jul 24 05:49:43 [48328] INFO: Missing 265316 mempool transactions, attempting to reload in bulk from esplora
Jul 24 05:49:46 [48328] INFO: Fetched 10000 of 265316 mempool transactions from esplora
Jul 24 05:49:48 [48328] INFO: Fetched 20000 of 265316 mempool transactions from esplora
Jul 24 05:49:51 [48328] INFO: Fetched 30000 of 265316 mempool transactions from esplora
Jul 24 05:49:54 [48328] INFO: Fetched 40000 of 265316 mempool transactions from esplora
Jul 24 05:49:56 [48328] INFO: Fetched 50000 of 265316 mempool transactions from esplora
Jul 24 05:49:59 [48328] INFO: Fetched 60000 of 265316 mempool transactions from esplora
Jul 24 05:50:01 [48328] INFO: Fetched 70000 of 265316 mempool transactions from esplora
Jul 24 05:50:04 [48328] INFO: Fetched 80000 of 265316 mempool transactions from esplora
Jul 24 05:50:06 [48328] INFO: Fetched 90000 of 265316 mempool transactions from esplora
Jul 24 05:50:07 [48328] DEBUG: Memory usage: 0.46 GB / 16.05 GB
Jul 24 05:50:09 [48328] INFO: Fetched 100000 of 265316 mempool transactions from esplora
Jul 24 05:50:11 [48328] INFO: Fetched 110000 of 265316 mempool transactions from esplora
Jul 24 05:50:14 [48328] INFO: Fetched 120000 of 265316 mempool transactions from esplora
Jul 24 05:50:17 [48328] INFO: Fetched 130000 of 265316 mempool transactions from esplora
Jul 24 05:50:19 [48328] INFO: Fetched 140000 of 265316 mempool transactions from esplora
Jul 24 05:50:22 [48328] INFO: Fetched 150000 of 265316 mempool transactions from esplora
Jul 24 05:50:24 [48328] INFO: Fetched 160000 of 265316 mempool transactions from esplora
Jul 24 05:50:27 [48328] INFO: Fetched 170000 of 265316 mempool transactions from esplora
Jul 24 05:50:30 [48328] INFO: Fetched 180000 of 265316 mempool transactions from esplora
Jul 24 05:50:33 [48328] INFO: Fetched 190000 of 265316 mempool transactions from esplora
Jul 24 05:50:35 [48328] INFO: Fetched 200000 of 265316 mempool transactions from esplora
Jul 24 05:50:38 [48328] INFO: Fetched 210000 of 265316 mempool transactions from esplora
Jul 24 05:50:41 [48328] INFO: Fetched 220000 of 265316 mempool transactions from esplora
Jul 24 05:50:43 [48328] INFO: Fetched 230000 of 265316 mempool transactions from esplora
Jul 24 05:50:46 [48328] INFO: Fetched 240000 of 265316 mempool transactions from esplora
Jul 24 05:50:48 [48328] INFO: Fetched 250000 of 265316 mempool transactions from esplora
Jul 24 05:50:51 [48328] INFO: Fetched 260000 of 265316 mempool transactions from esplora
Jul 24 05:50:53 [48328] INFO: Fetched 265667 of 265316 mem [...]

2023-07-24 05:54 UTC, merged

2023-07-25 04:26 UTC, junderw commented
post merge re-ACK. LGTM.