REST: Return an f64 for difficulty from the block value endpoint
mempool/electrs pull request #5
Opened 2023-03-10 03:17 UTC by junderw

Closes #3 

This doesn't require bumping rust-bitcoin dep.

This method was based on the method I used here: https://github.com/rust-bitcoin/rust-bitcoin/pull/1707

In the blog post here: https://blog.m-ou.se/floats/

2023-03-10 18:04 UTC, Kixunil commented on src/rest.rs
> +fn u256_to_f64(input: bitcoin::util::uint::Uint256) -> f64 {
FYI this type will be hidden in the next release (soon), so after bumping the version this whole code has to be deleted. I suggest you just wait for the release (unless this is urgent and you can't spend time resolving *other* breakages).

2023-07-16 10:54 UTC, wiz commented
@mononaut it would be nice if we can remove all the ugly hacks we added to get the difficulty from core instead of electrs for 3.0, wdyt?

2023-07-17 07:37 UTC, softsimon requested changes
There seem to be a difference in the rounding between Core and this.

Example 1: 000000000003ba27aa200b1cecaad478d2b00432346c3f1f3986da1afd33e506

14484.1623612254 (Core)
14484.162361225399 (Electrs with this PR)

Example 2: 000000000000034a7dedef4a161fa058a2d67a173a90155f3a2fe6fc132e0ebf
2864140.507810974 (core)
2864140.5078109736 (electrs)

2023-07-18 03:26 UTC, junderw commented
> There seem to be a difference in the rounding between Core and this.

I think this is acceptable.

In Element chat we have proven that even a 1:1 re-implementation of the Bitcoin Core logic results in differing precision.

This is likely due to the differences in the integer to float coercion in C++ vs. Rust.

Rust is more precise. C++ is less precise.

That said, it seems like different versions of Bitcoin Core (like the old ones that use older versions of C++) have differing precisions for the floats (due to C++ implementation of integer to float conversion changing).

If we want to always be === exactly to Bitcoin Core, there's no getting around asking Bitcoin Core directly for it.

2023-07-18 03:29 UTC, junderw commented
That said. If we want to use the 1:1 re-implementation (since I made it anyways) that would be fine. (the results would be the same, slightly more precise floats, but at least we can say "ported from Bitcoin Core" heh)

2023-07-19 00:49 UTC, junderw commented
https://github.com/serde-rs/json/issues/1041

@softsimon I found a way to make the difficulty match Bitcoin Core exactly, but the workaround will be very VERY ugly and hard to review. lol

I also extracted the values from Bitcoin Core for every difficulty period since the difficulty changed from 1.0... so I can add those as test cases to make sure we match exactly for every difficulty so far.

2023-07-20 21:37 UTC, junderw commented
Just in case anyone ever has need for all the difficulties on the blockchain, here's a script I wrote:

```bash
OUTPUT="const VECTORS: &[(&str, &str, u32, &str)] = &["

for i in $(seq 30240 2016 796320); do
	BHASH=$(bitcoin-cli getblockstats $i '["blockhash"]' | grep blockhash | cut -d\" -f4)
        HEADER="$(bitcoin-cli getblockheader $BHASH)"

	OUTPUT="$OUTPUT
    (
        \"Block height $i\",
        $(echo "$HEADER" | grep '"hash' | cut -d' ' -f4)
        0x$(echo "$HEADER" | grep 'bits' | cut -d\" -f4),
        \"$(echo "$HEADER" | grep 'difficulty' | cut -d' ' -f4 | cut -d',' -f1)\",
    ),"

done;

OUTPUT="$OUTPUT
];"

echo "$OUTPUT" > output.txt
```

<details>
 <summary>Click here for the output currently</summary>

```rust
const VECTORS: &[(&str, &str, u32, &str)] = &[
    (
        "Block height 30240",
        "000000000fa8bfa0f0dd32f956b874b2c7f1772c5fbedcb1b35e03335c7fb0a8",
        0x1d00ffff,
        "1",
    ),
    (
        "Block height 32256",
        "000000004f2886a170adb7204cb0c7a824217dd24d11a74423d564c4e0904967",
        0x1d00d86a,
        "1.182899534312841",
    ),
    (
        "Block height 34272",
        "000000002732d387256b57cabdcb17767e3d30e220ea73f844b1907c0b5919ea",
        0x1d00c428,
        "1.305062131591525",
    ),
    (
        "Block height 36288",
        "0000000040514b192e6ca247d83388bf11cb1d5e980610ae2c6324cbb0594b32",
        0x1d00be71,
        "1.344224970771029",
    ),
    (
        "Block height 38304",
        "0000000015bb50096055846954f7120e30d6aa2bd5ab8d4a4055ceacc853328a",
        0x1d008cc3,
        "1.818648536145414",
    ),
    (
        "Block height 40320",
        "0000000045861e169b5a961b7034f8de9e98022e7a39100dde3ae3ea240d7245",
        0x1c654657,
        "2.527738215072359",
    ),
    (
        "Block height 42336",
        "000000000b0078371753a9813d3f902008cec296451cf5d721e4660a2fba9612",
        0x1c43b3e5,
        "3.781179252033766",
    ),
    (
        "Block height 44352",
        "0000000026cdac72c9b2eb5ac20d987f7cb30118203528245a34ba1dc0f0d7a3",
        0x1c387f6f,
        "4.531081750070693",
    ),
    (
        "Block height 46368",
        "0000000027c99f9712286d6f3bd01f4d6de7b8bcce586c92f7a131b96d5d96c6",
        0x1c381375,
        "4.56516291033707",
    ),
    (
        "Block height 48384",
        "000000000f8bad9641203f9d788e72d55ff164f1a62a3e230df6f411f7d7d8fc",
        0x1c2a1115,
        "6.085476906000794",
    ),
    (
        "Block height 50400",
        "000000001af6e66db5628c7ba98501623bd23ea6d720571ffedf007973be07c9",
        0x1c20bca7,
        "7.819796993353832",
    ),
    (
        "Block height 52416",
        "00000000079f22d04081de2b3961e7bb1037051df3d178a4bc3258dae9a3ab63",
        0x1c16546f,
        "11.46431580551412",
    ),
    (
        "Block height 54432",
        "00000000021df73bddc56ff2bae4637099c096a1eba98ae631623d21b58877d6",
        0x1c13ec53,
        "12.84918314782378",
    ),
    (
        "Block height 56448",
        "00000000051a16879d044e2f58b60ecaedc9dc92a00416f9035ccc018e72f4ed",
        0x1c159c24,
        "11.84622814970471",
    ),
    (
        "Block height 58464",
        "0000000008c7b770615ca86782c41b97630c8fa23de40cabf3a2722224f9b799",
        0x1c0f675c,
        "16.61907875185736",
    ),
    (
        "Block height 60480",
        "000000000632e22ce73ed38f46d5b408ff1cff2cc9e10daaf437dfd655153837",
        0x1c0eba64,
        "17.38148815814011",
    ),
    (
        "Block height 62496",
        "00000000025825d92ecf024c9055af90f2fe92f5796aaffc61a3d95574bb3b76",
        0x1c0d3142,
        "19.40479632838217",
    ),
    (
        "Block height 64512",
        "000000000a20ed505ca567ec4611616790a1e3c49bc9bdd82ff6bd773e32db2a",
        0x1c0ae493,
        "23.50125722290317",
    ),
    (
        "Block height 66528",
        "0000000002216521d1a33de5bf19b3f8966395fbc81be449e2b2f1bdab2bd88f",
        0x1c05a3f4,
        "45.38582234101263",
    ),
    (
        "Block height 68544",
        "0000000000519051eb5f3c5943cdbc176a0eff4e1fbc3e08287bdb76299b8e5c",
        0x1c0168fd,
        "181.5432893640505",
    ),
    (
        "Block height 70560",
        "0000000000c4f919e27398ec17fe39ca0e8936596e7eeeb21f06d87e851df90e",
        0x1c010c5a,
        "244.2132230923753",
    ),
    (
        "Block height 72576",
        "00000000002897d721b6b31ad519e3e54a90741a24a019f23e41911a8c8b0d25",
        0x1c00ba18,
        "352.1612090680101",
    ),
    (
        "Block height 74592",
        "0000000000365da40798b3cea463f8307ff8b7bf828254721a7d4d270a35ee62",
        0x1c00800e,
        "511.7735342566043",
    ),
    (
        "Block height 76608",
        "00000000002d3c0657d352f28051fbfffda76ce99ddf5256dddebf4c9ee6cad4",
        0x1b692098,
        "623.3869598689275",
    ),
    (
        "Block height 78624",
        "00000000005174bca5fb1486b0cf216e2841560cd28db35839658a3583709983",
        0x1b5bede6,
        "712.8848645520973",
    ),
    (
        "Block height 80640",
        "0000000000307c80b87edf9f6a0697e2f01db67e518c8a4d6065d1d859a3a659",
        0x1b4766ed,
        "917.8307413015116",
    ),
    (
        "Block height 82656",
        "000000000024fc69f5415908b1960092a8e81b9d3b9a03c1133f5cb0a2d3c2af",
        0x1b31b2a3,
        "1318.670050153592",
    ),
    (
        "Block height 84672",
        "000000000006bee26b7ce695f7324381b48361ddde16c6922867e665a0df8430",
        0x1b2f8e9d,
        "1378.028165037326",
    ),
    (
        "Block height 86688",
        "000000000015bfe777e893c4ebd1307541792630c2932278bfe8cf3ae82668ce",
        0x1b1e7eca,
        "2149.021814946726",
    ),
    (
        "Block height 88704",
        "000000000012384edfbd167c7778aec3e84bb1795b907cc795912e643c2cff04",
        0x1b153263,
        "3091.736890411797",
    ),
    (
        "Block height 90720",
        "0000000000042751f341ee2dde050240cd8330401063dfdea21be270495bf360",
        0x1b0e7256,
        "4536.353723275037",
    ),
    (
        "Block height 92736",
        "00000000000615837a43bdec942b048bd28d48aba5d73b0c79617ccc71d56e68",
        0x1b098b2a,
        "6866.898648972739",
    ),
    (
        "Block height 94752",
        "00000000000612274477875b7ceb71488c060f9f718435122e0369a720c5f78f",
        0x1b081cd2,
        "8078.195257925088",
    ),
    (
        "Block height 96768",
        "00000000000481ef73efe6cb2ad1e9c1e3d1c46e712f6aeb6d5079b539d12246",
        0x1b055953,
        "12251.9997603745",
    ),
    (
        "Block height 98784",
        "0000000000043c4b0ed186109c36ce09e9af29b8ed0fdebcb909fa338877743d",
        0x1b04864c,
        "14484.1623612254",
    ),
    (
        "Block height 100800",
        "000000000000e383d43cc471c64a9a4a46794026989ef4ff9611d5acb704e47a",
        0x1b0404cb,
        "16307.42093852398",
    ),
    (
        "Block height 102816",
        "0000000000036e1b1c66c51814ee2f500f3e67d8e568f5606b91ad3359e68c0d",
        0x1b038dee,
        "18437.64439216629",
    ),
    (
        "Block height 104832",
        "0000000000018cfcff9528bdb69f53cce09e9705ed2681bb68f441b27b64cfa4",
        0x1b02fa29,
        "22012.38133799388",
    ),
    (
        "Block height 106848",
        "000000000000be2bc4445d0c929adaa79e6106528b8cc8651f1a0bba37bc0c1b",
        0x1b028552,
        "25997.87992881442",
    ),
    (
        "Block height 108864",
        "00000000000199206616e77986c26e500819a323feb51799b57c6fa6fbbe9850",
        0x1b01cc26,
        "36459.88692507513",
    ),
    (
        "Block height 110880",
        "0000000000004169640bb33c01f4417aefda88a1fabfa4f06f331d823df95fa2",
        0x1b012dcd,
        "55589.51812686866",
    ),
    (
        "Block height 112896",
        "000000000000cb6aeb7e251ed31a814d9631b5fe3d6994e00229f7ebbfae5344",
        0x1b00dc31,
        "76192.61934751371",
    ),
    (
        "Block height 114912",
        "000000000000a8c2cc7f45568c20d3498eba889a182dd72db10d7e7a98fb9f97",
        0x1b00f339,
        "68977.78463020959",
    [...]

2023-07-29 11:58 UTC, softsimon requested changes
Please rebase.

The Bitcoin Core emulated way with response as a "string" is acceptable.

2023-07-29 17:18 UTC, junderw commented
> Bitcoin Core emulated

Just to be clear, there is no way to emulate Bitcoin Core without compiling using the same C++ compiler as the current version of Core.

The only way we can match Bitcoin Core is to make an RPC call to Bitcoin Core and get the raw JSON response data before Rust parses it, copy that as a string into some cache, and return that string to the client calling electrs.

Also, Bitcoin Core could decide to use a new C++ edition and compiler tomorrow and the precision can suddenly change, so we need to make sure that our production servers always use the same exact version of Bitcoin Core and exact compiler (or we use the distributed compiled binaries).

And even then, mempool's difficulty precision might differ from some mining pool that decides they want to compile their own Bitcoin Core with a custom compiler or something.

---

tl;dr Yes, I can get the exact precision from Bitcoin Core. Yes I can cache it somewhere so that we're not calling RPC every block request... but no, even with that, we can not guarantee that the precision of the float will always be exactly the same as every other block explorer and every other mining pool.

The difficulty float is not meant to be a consensus critical piece of data, it's just "taking the consensus thing and making it human readable as "how many times the genesis block difficulty" for the plebs."... anyone who cares about the precision should be reminded that in float notation: `0.1 + 0.2 == 0.30000000000000004` is `true`.

I disagree that it is worthwhile to pursue this.

2023-07-29 20:27 UTC, junderw commented
Not to mention: All of our competitors are all over the place. Clearly if anyone is relying on the Difficulty being 15 decimals vs. 14 decimals........ they better be using Bitcoin Core with a fixed compiler....

<details>
 <summary>Click here to see other block explorers with screenshots</summary>

bitcoin-cli / RPC = 8 decimal places. (Also, 15 sig figs which breaks my assumptions of 16 sig figs)
![Screenshot_2023-07-29_13-11-51](https://github.com/mempool/electrs/assets/11246316/47b222a0-c9ed-46ac-a5eb-4271c81f2bc1)

Blockcypher = Doesn't show difficulty at all.
![Screenshot_2023-07-29_13-06-50](https://github.com/mempool/electrs/assets/11246316/51932352-93ec-46e8-8450-95667f52cfc1)

blockchain dot com = Shows 2 decimal places
![Screenshot_2023-07-29_13-07-14](https://github.com/mempool/electrs/assets/11246316/52eddafe-6672-4e64-810c-c3048a831045)

blockchair = Rounds up at 0.5
![Screenshot_2023-07-29_13-09-46](https://github.com/mempool/electrs/assets/11246316/95f8fa07-93ca-408e-b49f-c3aa023ac1bb)

blockstream info = Rounds down (uses electrs, so same behavior as we have currently)
![Screenshot_2023-07-29_13-13-50](https://github.com/mempool/electrs/assets/11246316/964838a6-533f-40b1-9601-be23ff4dbb2c)

btc dot com = .....??????????? what is this?????
![Screenshot_2023-07-29_13-22-29](https://github.com/mempool/electrs/assets/11246316/31bd0394-073a-41b3-8f8d-3ac1abba5d9d)

bitaps dot com = Rounds down
![Screenshot_2023-07-29_13-25-52](https://github.com/mempool/electrs/assets/11246316/738782c7-880a-4d7f-a9f6-35f5e066568c)

</details>

2023-07-30 06:47 UTC, softsimon commented
> I disagree that it is worthwhile to pursue this.

So your point is we should not pursue being close to Core with some hacks .. but rather use the more accurate simple calculation and return a Number in the API.

I concur.

2023-07-30 08:04 UTC, junderw commented
> I concur.

Ok, in that case, this PR is ready for merge.

2023-07-30 09:40 UTC, softsimon approved these changes
tested ACK @ [02aedf5bf41]

2023-07-30 09:42 UTC, merged

2023-07-31 07:52 UTC, wiz commented
We can't merge this yet because it will cause the difficulty adjustments to be wrong:

<img width="523" alt="Screenshot 2023-07-31 at 16 51 59" src="https://github.com/mempool/electrs/assets/232186/55a09336-bf1b-41a0-8563-f3d2eeb166b7">